### ISSUE TITLE
firefox (newer versions) does not stay connected to Cocalc

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#2875]
I have seen this repeatedly over past 3 weeks. It may be related to recent user issues connecting to CoCalc with Firefox on macOS. Seen with macOS 10.13.1, Firefox 59.0.2 (64-bit). No anti-virus or ad-blocker software installed. No browser extensions are enabled.

Sample timeline [added: see below for quicker way to replicate the problem]:
- 8:52 login to CoCalc
- 8:54 fans go on but no process showing over 10% CPU
- switch browser tabs so CoCalc session is not displayed
- 9:19 return to cocalc tab **CoCalc is no longer connected**. Other browser tabs and windows can be opened and refreshed normally.
  - see orange "connecting..." notification upper right, alternating with
"disconnected"
  - get message "Your connection is unstable or CoCalc is temporarily not available."
  - attempts to login by hitting refresh or closing and opening a new tab and entering CoCalc URL stall with blank CoCalc tab
  - login is possible after restarting the browser

Browser console log shows:
```
initializing prometheus client smc-6cc8c1ade66041fbb28e.cacheme.js:5:713630
websocket - connect smc-6cc8c1ade66041fbb28e.cacheme.js:5:1085992
websocket -- delete cookie smc-6cc8c1ade66041fbb28e.cacheme.js:5:1087744
websocket - connecting smc-6cc8c1ade66041fbb28e.cacheme.js:5:1085992
attempt: 1 and num_recent_disconnects: 0 smc-6cc8c1ade66041fbb28e.cacheme.js:5:3210873
unreachable code after return statement[Learn More] js:69:1217
[11.1s Δ 11.1s] websocket -- delete cookie smc-6cc8c1ade66041fbb28e.cacheme.js:5:53179
[11.1s Δ 0s] websocket - reconnect scheduled (attempt 1 out of 100000) smc-6cc8c1ade66041fbb28e.cacheme.js:5:53179
Firefox can’t establish a connection to the server at wss://cocalc.com/hub/?_primuscb=MDARKlu. 1-6cc8c1ade66041fbb28e.cacheme.js:2:917
[12.1s Δ 1s] websocket - connecting smc-6cc8c1ade66041fbb28e.cacheme.js:5:53179
[12.1s Δ 0.01s] attempt: 1 and num_recent_disconnects: 1 smc-6cc8c1ade66041fbb28e.cacheme.js:5:53179
[12.1s Δ 0s] attempt: 1 and num_recent_disconnects: 1 smc-6cc8c1ade66041fbb28e.cacheme.js:5:53179
The connection to wss://cocalc.com/hub/?_primuscb=MDARKlu was interrupted while the page was loading. 1-6cc8c1ade66041fbb28e.cacheme.js:2:917
Firefox can’t establish a connection to the server at wss://cocalc.com/hub/?_primuscb=MDARNbe. 1-6cc8c1ade66041fbb28e.cacheme.js:2:917
```

**Comment by DrXyzzy** [comment]
Also seen just now with Firefox 60.0 (64 bit).

**Comment by DrXyzzy** [comment]
Problem also seen after starting Firefox 60.0 in [safe mode](https://support.mozilla.com/en-US/kb/troubleshoot-firefox-issues-using-safe-mode?redirectlocale=en-US&redirectslug=Safe+Mode), which disables extensions and non-default theme.

**Comment by haraldschilly** [comment]
My feeling is this has to do with removing cookies, e.g. there is 2x `misc_page.delete_cookie('SMCSERVERID3')`  in the client related to establishing the primus connection. It's the only reason I can think of, why it works after firefox starts up, but then fails after subsequent refreshes. It's maybe hard to test in an embedded project, because some authentication still goes through the main production hubs. And well, deleting that `SMCSERVERID3` cookie alone might not be the culprit, but I think its it's worth to investigate.

**Comment by haraldschilly** [comment]
My cookie idea is probably bogus. More interesting is searching bugzilla for status code 425!

https://bugzilla.mozilla.org/show_bug.cgi?id=1453204

**Comment by DrXyzzy** [comment]
adding `blocked` label pending upstream fix e.g. https://bugzilla.mozilla.org/show_bug.cgi?id=1453204

**Comment by haraldschilly** [comment]
I uploaded them a ~30mb logfile with all networking details in firefox. I hope that helps them to figure out what's going on.

**Comment by DrXyzzy** [comment]
As pointed out by @haraldschilly, the bug appears [fixed](https://bugzilla.mozilla.org/show_bug.cgi?id=1453204#c29) in Firefox Nightly 63.0a1 (2018-07-13) (64-bit) and appears approved for uplift to 62 beta 9. I verified the bug is gone in macOS 10.13.3.

**Comment by DrXyzzy** [comment]
Bug appears fixed in Firefox current beta, 62.0b11 (64-bit).

**Comment by williamstein** [comment]
>  in case someone hasn't updated for version 60?

Yes -- This is probably going to happen periodically for months to come...

**Comment by llimeht** [comment]
Firefox 60 is an ESR which means that it does get fixes backported to it and this one seems fixed in 60.2.0 according to the metadata on the [firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1453204) (and I can't reproduce it with 60.2.0esr). Being an ESR, it remains a supported release until [Oct 2019](https://www.mozilla.org/en-US/firefox/organizations/) so many will be using it into the future; can the preflight check not complain about Firefox >= 60.2?

**Comment by DrXyzzy** [comment]
Thanks @llimeht for the suggestion. I have verified that FF 60.2.0esr does have the fix, so the CoCalc warning should not appear for that version.

I believe we should keep FF 61.x versions on the warning list. For example, FF 61.0.2 has the bug.

**Comment by williamstein** [comment]
>  I have verified that FF 60.2.0esr does have the fix

Yep, I just installed it on my pixelbook with crostini (in debian stable) and it doesn't exhibit this bug.

I don't know how to change our version check code though to make this check... (I haven't really thought much about it).  Somebody should do so soon. PR's welcome!!   The code to change is here:

https://github.com/sagemathinc/cocalc/blob/master/src/webapp-lib/preflight-checks.ts

**Comment by DrXyzzy** [comment]
I should have included in prior note that I was testing versions of Firefox on macOS 10.13.6.

The browser user agent string is used in CoCalc for the version check in `preflight-checks.ts`. But the user agent version sent is apparently not updated in the ESR version, i.e. it still shows as "60.0" even when browser version is "60.2.0esr". You can see this by viewing `about:support` in FF 60.2.0esr  and checking the entries for "Version" and "User Agent".

**Comment by haraldschilly** [comment]
collecting build IDs for firefox:

my own FF

```
navigator.userAgent
"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"
navigator.buildID
"20180905221508"
```

browserstack for FF 60 on Win 10 (whatever they have there)

![screenshot from 2018-09-12 17-04-28](https://user-images.githubusercontent.com/207405/45434133-f329cb00-b6ad-11e8-9760-d4c989fbc8cc.png)

**Comment by haraldschilly** [comment]
and here is 60.2esr (fresh download in my linux machine)

```
navigator.userAgent
"Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0"
navigator.buildID
"20180903060751"
```

idea: for version 60, we pick the first 8 chars from the buildID, and do a lexical comparison with the known good build ID that's shown here, and hence we know it's a good version or a later version 60 esr release.

**Comment by haraldschilly** [comment]
I'm closing this. We know what's going on and even narrowed down the warning msg to exclude the patched ESR release

**Comment by matthew-brett** [comment]
Does Firefox know that the bug has returned?
