### ISSUE TITLE
ipywidgets and 3D graphs not working in self-hosted (docker) version

### ISSUE THREAD

**Issue by electron2302** [sagemathinc/cocalc#3813]
Hello,

First of all, thanks a lot for this awesome project. <3 
I am using it for a group assignments in my computer science course, and we all love it.
But I'm somehow not able to display ipywidgets and 3D graphs, for the graphs, there is a button that comes up with which says "Load Viewer...", but if you press it nothing happens, and the ipywidgets dont show up as well. (on cocalc.com they do, with the same code)

I found this error in the browser console:
`https://cocalc.my.domain/83dba49d-83c7-47e0-800e-85b311918cfe/port/jupyter/static/@jupyter-widgets/base.js?v=20190507194142 -> 404 Not Found`

And they dont work in the "Plain Jupyter Classic Server" either

has someone any ideas on how I can resolve that or what further information would you need to do so ?

I had hoped that it would work, since it was a very recently resolved by @williamstein in https://github.com/sagemathinc/cocalc/issues/1930#issuecomment-487231691_

**Comment by williamstein** [comment]
> I had hoped that it would work, since it was a very recently resolved by @williamstein

Indeed -- I just finished implementing widgets only a week ago.   The docker image needs to be updated to support widgets.  @DrXyzzy is working on this -- what's the status?  I also think there is a workaround involving installing the python ipywidgets code...

**Comment by DrXyzzy** [comment]
I pushed a new image to dockerhub a little while ago and am testing it now. There's a PR for this, but I need to make a small change to it. Should be done in a little while.

**Comment by DrXyzzy** [comment]
@electron2302, thanks for getting in touch!

The latest cocalc image at docker hub has working ipywidgets. You should pick up the fix if you upgrade your cocalc-docker install as explained here: https://github.com/sagemathinc/cocalc-docker#upgrade

I'm updating cocalc-no-agpl, too, and will push that shortly.

BTW, I think this issue is the same as sagemathinc/cocalc-docker#51.

**Comment by DrXyzzy** [comment]
I just now pushed another revision of the CoCalc docker image around Thu May  9 04:45:40 UTC 2019.

The previous revision had ipywidgets working for Sagemath and Python 3 Ubuntu kernels, but not Python 2 Ubuntu kernel. Now fixed.

**Comment by electron2302** [comment]
Since the last change to the docker image was on the same day, where @williamstein, sad it was done, i assumed it would have been in the docker image already, But now the ipywidgets work great indeed :) 

But i still have the Problem that 3D graphs are not loading, not even in the "Plain Jupyter Classic Server" - any ideas on why they are not loading ?  
One example would be
```
t = var('t')
parametric_plot((t, sin(t), cos(t)), (t, 0, 5*pi))
```

**Comment by DrXyzzy** [comment]
@electron2302, thank you for pointing out the additional problem with 3D plots. Please see the [cocalc-docker](https://github.com/sagemathinc/cocalc-docker) repo on GitHub for follow-up. The 3D problem you're seeing is probably a variant of known issue sagemathinc/cocalc-docker#35. I'm looking into that issue this week.

**Comment by electron2302** [comment]
Yes, that is the same issue, and the workaround also works fine, thanks for pointing to that @DrXyzzy
